#!/usr/bin/env bash
# ============================================================
# add_mods.sh — MechanicalForge packwiz import script
#
# Uses exact Modrinth IDs and CurseForge project IDs from
# the MechanicalForge.md mod list.
#
# Prerequisites:
#   - packwiz installed and on your PATH
#   - Run `packwiz init` first to create pack.toml
#   - Run this script from your pack's root directory
#
# Usage:
#   chmod +x add_mods.sh
#   ./add_mods.sh 2>&1 | tee add_mods.log
# ============================================================

FAILED_LOG="failed_mods.txt"
> "$FAILED_LOG"

mr() {
    local id="$1" name="$2"
    echo "  [Modrinth] $name ($id)"
    if ! packwiz modrinth add "$id"; then
        echo "    ✗ Failed — logged"
        echo "modrinth: $name  ($id)" >> "$FAILED_LOG"
    fi
}

cf() {
    local id="$1" name="$2"
    echo "  [CurseForge] $name ($id)"
    if ! packwiz curseforge add "$name"; then
        echo "    ✗ Failed — logged"
        echo "curseforge: $name  (project $id)" >> "$FAILED_LOG"
    fi
}

# NOTE: Two mods have no URL in the markdown — add manually:
#   .connector
#   VMH - Variable Mob Height

echo "=== Ad Astra & Addons ==="
mr 3ufwT9JF   "Ad Astra"
mr 1Z4JHpyZ   "Ad Astra: More Structures"
mr IHyWDPnp   "Ad Astra: Per Spatium Et Tempus"
cf 1386899    "Ad Astra: Structures Overhaul"
mr u9zCDhSS   "Dungeon And Village: Ad Astra"
mr pHMBwRFe   "Simple Structure Ad Astra 1.20.1"
mr x187Px7Z   "ad astra tools"

echo "=== Applied Energistics 2 ==="
mr XxWD5pD3   "Applied Energistics 2"
cf 892005     "ExtendedAE"
mr Ck4E7v7R   "GuideME"
mr E6BFl96N   "ME Requester"

echo "=== Create & Addons ==="
mr LNytGWDc   "Create"
mr bFyxs7LI   "Create Ad Astra Recipes"
mr 16DuAG4k   "Create Bitterballen"
mr kU1G12Nn   "Create Crafts & Additions"
mr sMvUb4Rb   "Create Deco"
mr JWGBpFUP   "Create Enchantment Industry"
mr UbFnAd4l   "Create Jetpack"
mr ResbpANg   "Create Ore Excavation"
mr Dq3STxps   "Create Railways Navigator"
mr GmjmRQ0A   "Create Slice & Dice"
cf 1085408    "Create: Additional Lights"
mr gJ5afkVv   "Create: Bells & Whistles"
mr aqYNR6rI   "Create: Copper and Zinc"
mr UT2M39wf   "Create: Copycats+"
mr 5bgqgixq   "Create: EMI Schematics"
mr PSQLOzw4   "Create: Enlightend"
mr r4Knci2k   "Create: Interiors"
mr BBhCMftF   "Create: Jetpack Curios"
mr FTeXqI9v   "Create: New Age"
mr fmudhH0S   "Create: Propulsion"
mr ZzjhlDgM   "Create: Steam 'n' Rails"
mr IAnP4np7   "Create: Structures"
mr RYJzdkDr   "Create: Threaded Trains"
mr WNRCHiE5   "Extended Wrenches"
mr Q4F90RHI   "create_armor_trims"

echo "=== Mekanism ==="
cf 268560     "Mekanism"
cf 345425     "Mekanism: Additions"
cf 268566     "Mekanism: Generators"
cf 1205233    "Mekanism: More Machine"
cf 268567     "Mekanism: Tools"
mr 5kBJRF84   "Mekanism x Create: Northstar"
mr XuHYu7cF   "Northstar"

echo "=== Refined Storage ==="
mr KDvYkUg3   "Refined Storage"

echo "=== World / Dimensions ==="
mr aSIFLYIc   "Better End"
mr SwolYSb8   "Enlightend"
mr ZVzW5oNS   "Incendium"
mr wiPmcmNp   "Infernal Expansion"
cf 422981     "Just Another Mining Dimension"
mr Tkikq67H   "Regions Unexplored"
mr YhmgMVyu   "The Aether"
mr X8s97ySO   "The Outer End"
cf 227639     "The Twilight Forest"
mr 49C5QgTK   "Fragmentum"
mr v3UlehfS   "Jaden's Nether Expansion"
mr TYOsE3t5   "Eye to city"
cf 870210     "Trenzalore"

echo "=== Structures ==="
mr sc9lpPiU   "Medieval Buildings"

echo "=== Decoration / Furniture ==="
mr pJmCFF0p   "Handcrafted"
mr fFEIiSDQ   "Supplementaries"
mr 6iTJugQR   "Amendments"

echo "=== Travel / Transport ==="
cf 1281346    "BlastTravel-Reborn"
mr x3HZvrj6   "Immersive Aircraft"
cf 570050     "Little Logistics"
mr 9qdTHi0q   "Man of Many Planes"
mr V5ujR2yw   "Valkyrien Skies 2"
mr VW7RrrFu   "Valkyrien Skies Tournament Reforged"
mr vuNeeDyl   "aleki's Nifty Ships"
mr FXDpZRJG   "Trackwork Mod"

echo "=== Mobs / Creatures ==="
mr Yd4wb5wZ   "Critters and Companions"
mr vYSi4UOX   "Unusual Fish Mod"
mr BFzwTnQr   "Animights"
mr AtB5mHky   "What Are They Up To"

echo "=== Equipment / Gear ==="
mr eE2Db4YU   "Immersive Armors"
mr AtT9wm5O   "Radiant Gear"
mr OeM72JOF   "Scuba Gear"
cf 557556     "Responsive Shields"
mr SzzJttH8   "Timeless & Classics Guns: Zero"
mr arHQz0zX   "Foxs Elytra Mod"

echo "=== Storage / Logistics ==="
mr joEfVgkn   "Carry On"
mr TyCTlI4b   "Sophisticated Backpacks"
mr nmoqTijg   "Sophisticated Core"
mr 4QrnfueM   "Trash Cans"
mr EltpO5cN   "Lootr"

echo "=== Farming / Utility ==="
mr Cnejf5xM   "Right Click Harvest"
mr abooMhox   "Tree Harvester"
mr WRaRZdTd   "Universal Sawmill"
mr 5ZuwMbpk   "Molten Metals"
mr tagwiZkJ   "Polymorph"

echo "=== UI / HUD / Client ==="
mr EsAfCjCV   "AppleSkin"
mr Y5Ve4Ui4   "Antique Atlas"
mr Q2OqKxDG   "Better Advancements"
mr 8shC1gFX   "BetterF3"
cf 972468     "Chat Impressive Animation"
mr yoJJjRRE   "ClearDespawn"
mr K0AkAin6   "ClientSort"
mr Wnxd13zP   "Clumps"
mr xv94TkTM   "Controlling"
mr DFqQfIBR   "CraftPresence"
mr ETlrkaYF   "Cubes Without Borders"
mr WEg59z5b   "Default Options"
mr aLcHfalx   "Draggable Lists"
mr v3CYg2V9   "Drippy Loading Screen"
mr fRiHVvU7   "EMI"
mr 11hKNQb2   "EMI Enchants"
mr sG4TqDb8   "EMI Ores"
mr j2HhbEE7   "EMI Trades"
mr 705gWllI   "EMIffect"
mr Wq5SjeWM   "FancyMenu"
mr cVNW5lr6   "Highlighter"
mr b1fMg6sH   "Item Borders"
mr nvQzSEkH   "Jade"
mr xuDOzCLy   "Jade Addons"
mr GAJkSU0A   "Jade Modded Entities"
mr zNKzjsZM   "Jade-VS"
mr u6dRKJwZ   "Just Enough Items"
mr iAiqcykM   "Just Zoom"
mr 4zpN0syd   "LanguageReload"
mr wLINU2AB   "Measurements"
mr wOIKNYYX   "More Chat History Reforged"
mr aC3cM3Vq   "Mouse Tweaks"
mr MPCX6s5C   "NotEnoughAnimations"
cf 715660     "Obscure Tooltips"
mr VYRu7qmG   "Observable"
mr E0L8mfJZ   "ObsidianUI"
mr gF3BGWvG   "Open Parties and Claims"
mr RLzHAoZe   "Resourcify"
mr 1KiJRrTg   "Screenshot to Clipboard"
mr fuuu3xnx   "Searchables"
mr vqqx0QiE   "Sodium Extras"
mr Es5v4eyq   "Sodium Options API"
mr 4q8UOK1d   "Subtle Effects"
mr 4KjqhPc9  "Surveyor Map Framework"

echo "=== Visuals / Shaders / Rendering ==="
mr 1IjD5062   "Continuity"
mr 4I1XuqiY   "Entity Model Features"
mr BVzZfTc1   "Entity Texture Features"
mr NNAgCjsB   "EntityCulling"
mr r0camchr   "Explosive Enhancement"
mr hB899VmG   "Exposure"
mr s9gIPDom   "Figura"
mr KSyWOxT5   "FlickerFix"
mr p19vrgc2   "Fusion"
mr XYnKrsxH   "Inventory Particles"
mr gPCdW0Wr   "Make Bubbles Pop"
mr GchcoXML   "Oculus"
cf 421897     "Particle Rain"
cf 1219053    "Particular"
mr reCfnRvJ   "RyoamicLights"
mr Fq4tBIiz   "Serious Player Animations"
mr E0SdeAoH   "Wakes"

echo "=== Audio ==="
mr IgftU6Mn   "Cool Rain"
mr diy3cBDJ   "ImmersiveThunder"
mr dLfueQtY   "Presence Footsteps [FORGE]"
mr 9eGKb6K1   "Simple Voice Chat"
mr qyVF9oeo   "Sound Physics Remastered"
mr 8GRDQ9XB   "Sound of Rain"
mr CVT4pFB2   "Melody"
mr FBf5onys   "Meowing?"

echo "=== Gameplay QoL ==="
mr tNmWwdI2   "Barebones McQoy"
mr 4HeIHvIP   "Jump Over Fences"
mr t5W7Jfwy   "Pehkui"
mr rex9wwpz   "Spawn"
mr D3W7NSps   "Why is there Auto Jump?"
mr 9wv7LuMc   "ImmersiveUI"
mr P8STLvzB   "Perception"
cf 968067     "Wardrobe"

echo "=== Server / Admin ==="
mr lL2MtE37   "Bad Wither No Cookie Reloaded"
mr KJhXPbHQ   "Better Compatibility Checker"
mr rLLJ1OZM   "CoroUtil"
mr rbJ7eS5V   "Discord Integration"
mr 8oGVUFuX   "GriefLogger"
mr Vebnzrzj   "LuckPerms"
mr qQyHxfxd   "No Chat Reports"
mr z440MEwJ   "No Chat Restrictions"
mr 9WJeSpTH   "No Report Button"
mr hg77g4Pw   "No Telemetry"

echo "=== Plushies / Cosmetics ==="
mr J7XYBmDh   "Amazing Digital Plushies"
mr L45eoNGD   "Gen's Villager Hats"
mr VLpCVEoM   "Panda Plushies!"
mr L5MLckDN   "Perfect Plushies"

echo "=== Libraries / APIs ==="
mr lhGA9TYQ   "Architectury"
mr obMZk452   "BCLib"
mr MBAkmtvl   "Balm"
mr VsM5EDoI   "Blueprint"
mr 2u6LRnMa   "Botarium"
mr 9s6osm5g   "Cloth Config v10 API"
mr e0M1UDsY   "Collective"
cf 1148422    "Connector Extras"
mr vvuO3ImH   "Curios API"
mr ZS3lIxKu   "Data API"
mr sbIsGaOV   "DragonLib"
mr 6YTvv3aI   "Elysium"
mr hYykXjDp   "Fzzy Config"
mr 8BmcQJ2H   "GeckoLib 4"
mr UhW5uCKw   "Glodium"
mr 5faXoLqX   "Iceberg"
mr IYY9Siz8   "JamLib"
mr hAnl9nbm   "Knight Lib"
mr ordsPcFz   "Kotlin for Forge"
mr 1vrSzlao   "KotlinLangForge"
mr J81TRJWm   "Konkrete"
mr twkfQtEc   "Moonlight Library"
mr ffLDUGbm   "MossyLib"
mr RH2KUdKJ   "OctoLib"
mr nU0bVIaL   "Patchouli"
mr gedNE4y2   "Player Animator"
mr 1OE8wbN0   "Prism"
mr G1hIVOrD   "Resourceful Lib"
mr M1953qlQ   "Resourcefulconfig"
mr LN9BxssP   "SuperMartijn642's Config Library"
mr rOUBggPv   "SuperMartijn642's Core Lib"
mr kkmrDlKT   "TerraBlender"
mr nT86WUER   "UniLib"
mr 5T56XRUO   "WunderLib"
mr 1eAoo2KR   "YetAnotherConfigLib"

echo "=== Performance ==="
mr g96Z4WVZ   "BadOptimizations"
mr LQ3K71Q1   "Dynamic FPS"
cf 908741     "Embeddium"
mr uXXizFIs   "Ferrite Core"
mr 5ZwdcRci   "ImmediatelyFast"
mr NRjRiSSD   "Memory Leak Fix"
mr nmDcB62a   "ModernFix"
mr KuNKN7d2   "Noisium"
mr FFeAJNCx   "PreloadingTricks"
mr QdG47OkI   "Model Gap Fix"

echo "=== Compat / Bridges ==="
cf 889079     "Forgified Fabric API"
cf 890127     "Sinytra Connector"

echo ""
echo "========================================"
echo "Finished! Check $FAILED_LOG for any failures."
echo ""
echo "Mods with no URL — add manually:"
echo "  - .connector"
echo "  - VMH - Variable Mob Height"
echo "========================================"