name = "GalaxyPack 26Q2"
author = "Pencil Fox Studios"
version = "0.0.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "5dac3548ba43dc604fef8d6329b301497693cc3055c873ceba757fe20f7b3d4a"

[versions]
forge = "47.4.16"
minecraft = "1.20.1"
