name = "GalaxyPack 26Q2"
author = "Pencil Fox Studios"
version = "0.0.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "c16b648977fdc7ae7754eae33cfdf17cbec6b3f0e44e0d45e0fe4b8f77762e9a"

[versions]
forge = "47.4.16"
minecraft = "1.20.1"
