name = "GalaxyPack 26Q2"
author = "Pencil Fox Studios"
version = "0.0.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "c7e4bcec33c43a97827adc318a9d1be06aa6e6ce8730353312369121e03dec11"

[versions]
forge = "47.4.10"
minecraft = "1.20.1"

[options]
acceptable-game-versions = []
