name = "Foxtoberfest"
author = "Pencil Fox Studios"
version = "1.1.6"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "d33ca406b5aa56a54343d6a205b25b70fbb6ea3a3e51999e026a042794dea71d"

[versions]
fabric = "0.17.2"
minecraft = "1.21.1"
