name = "Foxtoberfest"
author = "Pencil Fox Studios"
version = "1.2.4"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "775a2e19b66cf54b3ed64b10b7585f6aceae9c2bdeacc27111614d5745d49db0"

[versions]
fabric = "0.17.2"
minecraft = "1.21.4"
