name = "Foxtoberfest"
author = "Pencil Fox Studios"
version = "1.2.4"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "322aae39422332a2252e0a64cb97771f6207510fbe15e112646fbf11ac14c843"

[versions]
fabric = "0.17.2"
minecraft = "1.21.4"
