name = "Foxtoberfest"
author = "Pencil Fox Studios"
version = "1.1.4"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "aed4ecec15855b705a6a155f190dcef30b4147ed80267567d59d957c5ca7e824"

[versions]
fabric = "0.17.2"
minecraft = "1.21.1"
