name = "Foxtoberfest"
author = "Pencil Fox Studios"
version = "1.2.5"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "2074cdc32de5e618092571e6bbaa73db4f02f095b2f86ebd4696cb0e5f30811b"

[versions]
fabric = "0.17.2"
minecraft = "1.21.4"
