name = "Foxtoberfest"
author = "Pencil Fox Studios"
version = "1.2.3"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "654c7c7ecad9b1c8be37e7dd4e5caf7cd9c460ab26558f4406b0d06048f1e637"

[versions]
fabric = "0.17.2"
minecraft = "1.21.4"
