name = "Foxtoberfest"
author = "Pencil Fox Studios"
version = "1.1.6"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "5ee172f8d9a4051a94927ae9d47075f1b69590f3518be2b4ec3a08bd6fe14dbd"

[versions]
fabric = "0.17.2"
minecraft = "1.21.1"
