name = "Foxtoberfest"
author = "Pencil Fox Studios"
version = "1.2.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "e60595bbbcd70983162f1c6de506a5894fc23062c2ca466f1a28dceaf3582bc3"

[versions]
fabric = "0.17.2"
minecraft = "1.21.4"
