name = "Foxtoberfest"
author = "Pencil Fox Studios"
version = "1.0.3"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "402cc6badecf61ee173caffe9158ad79a4696e982d00259557f2da91bbf398db"

[versions]
fabric = "0.17.2"
minecraft = "1.20.1"
