name = "Foxtoberfest"
author = "Pencil Fox Studios"
version = "1.2.2"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "4ac24c3083fb380eba0704fc781cc9baa9d132704ecd08804a2a0084bd706cd9"

[versions]
fabric = "0.17.2"
minecraft = "1.21.4"
