name = "Foxtoberfest"
author = "Pencil Fox Studios"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "627e2193dd60cbe6cadc5fd34beb5044f59dd885ab4f0ab9d3e6053b964a6d38"

[versions]
fabric = "0.17.2"
minecraft = "1.20.1"
