name = "Foxtoberfest"
author = "Pencil Fox Studios"
version = "1.1.2"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "880754e805275351d0982c2204343c113b8c994f0a92fce171714b5c35252b6a"

[versions]
fabric = "0.17.2"
minecraft = "1.21.1"
