name = "Foxtoberfest"
author = "Pencil Fox Studios"
version = "1.2.5"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "73cd5c041421e9a233d5708d32279be72511f28f017bbf89ffea6029ccdfa5ff"

[versions]
fabric = "0.17.2"
minecraft = "1.21.4"
