name = "Foxtoberfest"
author = "Pencil Fox Studios"
version = "1.0.6"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "819717056a130c930ba8816aaf2c402fdd82e42198cc3842e9a1ea2086551ace"

[versions]
fabric = "0.17.2"
minecraft = "1.20.1"
