name = "Foxtoberfest"
author = "Pencil Fox Studios"
version = "1.0.7"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "aaa28acdbeb7ccbef810563dcc6d01d73f238fb32d7cbb97deb98b20cef496ed"

[versions]
fabric = "0.17.2"
minecraft = "1.20.1"
