name = "Foxtoberfest"
author = "Pencil Fox Studios"
version = "1.2.2"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "c49e3256d6a0b5a83f62ede6ff06e677121ecc3b37af7aa2c5706e47baeeb345"

[versions]
fabric = "0.17.2"
minecraft = "1.21.4"
