name = "Foxtoberfest"
author = "Pencil Fox Studios"
version = "1.0.9"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "cfaf439bcd476a58fb96a99016fe74d3d71b78ce6727ad0a080ac2a14b89be44"

[versions]
fabric = "0.17.2"
minecraft = "1.21.1"
