name = "Foxtoberfest"
author = "Pencil Fox Studios"
version = "1.0.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "5e1d5e2293319d868c8ea9b57c4e82d65c371a97b0ad8c177c22f1f44ccc3d9d"

[versions]
fabric = "0.17.2"
minecraft = "1.20.1"
