name = "Foxtoberfest"
author = "Pencil Fox Studios"
version = "1.1.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "6f22e2fc896bc30c995c478a0f0b4da898c6e6b9dbdb8f3c450c9a3876ed6685"

[versions]
fabric = "0.17.2"
minecraft = "1.21.1"
