name = "Foxtoberfest"
author = "Pencil Fox Studios"
version = "1.2.6"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "4f7b49fffd9be5f2caf321f2d475b8ade5ce551a331b4c42eea7d2ed8d434a74"

[versions]
fabric = "0.17.2"
minecraft = "1.21.4"
