name = "Foxtoberfest"
author = "Pencil Fox Studios"
version = "1.2.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "d047e9d91cf8e948c5eeaea3308791c2448c1859781d82271c4711b66d9ae0d4"

[versions]
fabric = "0.17.2"
minecraft = "1.21.4"
